Description: Resources for the Brighid Static Assets Pipeline
Transform: AWS::Serverless-2016-10-31
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket

  StaticAssetsSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: brighid-static-assets-build
      ServiceRole: !ImportValue cfn-utilities:BuilderRoleArn
      EncryptionKey: !ImportValue cfn-utilities:ArtifactKeyArn
      Environment:
        PrivilegedMode: true
        Image: aws/codebuild/standard:4.0
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ASSETS_SOURCE_BUCKET
            Value: !Ref StaticAssetsSourceBucket
        Type: LINUX_CONTAINER
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucket
        Name: buildResults.zip
        NamespaceType: BUILD_ID
        Packaging: ZIP
      Source:
        Type: GITHUB
        Location: https://github.com/cythral/brighid-infrastructure.git
        BuildSpec: cicd/tasks/build-static-asset.yml

  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: brighid-static-assets-pipeline
      Role: !ImportValue cfn-utilities:MasterRoleArn
      DefinitionUri: ./pipeline.asl.yml
      DefinitionSubstitutions:
        BuildProject: !Ref BuildProject
        S3DeploymentFunctionArn: !ImportValue cfn-core:S3DeploymentFunctionArn
        DevRoleArn: !ImportValue cfn-metadata:DevAgentRoleArn
        ProdRoleArn: !ImportValue cfn-metadata:ProdAgentRoleArn
        StaticAssetsSourceBucket: !Ref StaticAssetsSourceBucket
        ApprovalNotificationFunction: !ImportValue cfn-core:ApprovalNotificationFunctionArn
        ArtifactStore: !Ref ArtifactBucket
      Events:
        S3Event:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source: [aws.s3]
              detail-type: [AWS API Call via CloudTrail]
              detail:
                eventSource: [s3.amazonaws.com]
                eventName: [PutObject,CompleteMultipartUpload]