Description: Resources for the Brighid Static Assets Pipeline
Transform: AWS::Serverless-2016-10-31
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetBucketAcl
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${ArtifactBucket}
              - !Sub arn:aws:s3:::${ArtifactBucket}/*
            Principal:
              Service: cloudtrail.amazonaws.com

  StaticAssetsSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  StaticAssetsCloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: ArtifactBucketPolicy
    Properties:
      S3BucketName: !Ref ArtifactBucket
      S3KeyPrefix: source-bucket-events
      IsLogging: true
      EventSelectors:
        - DataResources:
            - Type: AWS::S3::Object
              Values: 
                - !Sub arn:aws:s3:::${StaticAssetsSourceBucket}/

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: brighid-static-assets-build
      ServiceRole: !ImportValue cfn-utilities:BuilderRoleArn
      EncryptionKey: !ImportValue cfn-utilities:ArtifactKeyArn
      Environment:
        PrivilegedMode: true
        Image: aws/codebuild/standard:4.0
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ASSETS_SOURCE_BUCKET
            Value: !Ref StaticAssetsSourceBucket
        Type: LINUX_CONTAINER
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucket
        Name: buildResults.zip
        NamespaceType: BUILD_ID
        Packaging: ZIP
      Source:
        Type: GITHUB
        Location: https://github.com/cythral/brighid-infrastructure.git
        BuildSpec: cicd/tasks/build-static-asset.yml

  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: brighid-static-assets-pipeline
      Role: !ImportValue cfn-utilities:MasterRoleArn
      DefinitionUri: ./pipeline.asl.yml
      DefinitionSubstitutions:
        BuildProject: !Ref BuildProject
        S3DeploymentFunctionArn: !ImportValue cfn-core:S3DeploymentFunctionArn
        DevRoleArn: !ImportValue cfn-metadata:DevAgentRoleArn
        StaticAssetsSourceBucket: !Ref StaticAssetsSourceBucket
      Events:
        S3Event:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source: [aws.s3]
              detail-type: [AWS API Call via CloudTrail]
              detail:
                eventSource: [s3.amazonaws.com]
                eventName: [PutObject,CompleteMultipartUpload]