Description: Common Brighid Infrastructure
Parameters:
  EnableServiceStopping:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Description: Whether or not to enable service stopping on the cluster

  BaseDomainName:
    Type: String
    Description: Base Domain Name to use for Brighid Services.

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: brighid
      Tags:
        - Key: ENABLE_SERVICE_STOPPING
          Value: !Ref EnableServiceStopping

  RequestTopic:
    Type: AWS::SNS::Topic

  ResponseTopic:
    Type: AWS::SNS::Topic

  ServiceRegistry:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: !Ref BaseDomainName
      Description: Internal DNS Namespace for Brighid Services.
      Vpc: !ImportValue cfn-utilities:VpcId

  TestSecret:
    Type: Custom::Secret
    Properties:
      ServiceToken: !ImportValue cfn-secret-resource:SecretLambdaArn
      KeyId: alias/SecretsKey
      Plaintext: test

Outputs:
  ClusterName:
    Value: !Ref Cluster
    Description: Name of the ECS Cluster
    Export:
      Name: !Sub ${AWS::StackName}:ClusterName

  RequestTopicArn:
    Value: !Ref RequestTopic
    Description: ARN of the Request / Command Topic
    Export:
      Name: !Sub ${AWS::StackName}:RequestTopicArn

  ResponseTopic:
    Value: !Ref ResponseTopic
    Description: ARN of the Response Topic
    Export:
      Name: !Sub ${AWS::StackName}:ResponseTopicArn

  ServiceRegistry:
    Value: !Ref ServiceRegistry
    Description: Namespace ID of the Service Registry
    Export:
      Name: !Sub ${AWS::StackName}:ServiceRegistry

  ServiceRegistryName:
    Value: !Ref BaseDomainName
    Description: Name of the Service Registry
    Export:
      Name: !Sub ${AWS::StackName}:ServiceRegistryName

  TestSecret:
    Value: !GetAtt TestSecret.Arn
    Description: ARN of the test secret
    Export:
      Name: !Sub ${AWS::StackName}:TestSecret