Description: Common Brighid Infrastructure
Parameters:
  EnableServiceStopping:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Description: Whether or not to enable service stopping on the cluster

  BaseDomainName:
    Type: String
    Description: Base Domain Name to use for Brighid Services.

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: brighid
      Tags:
        - Key: ENABLE_SERVICE_STOPPING
          Value: !Ref EnableServiceStopping

  RequestTopic:
    Type: AWS::SNS::Topic

  ResponseTopic:
    Type: AWS::SNS::Topic

  ServiceRegistry:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: !Ref BaseDomainName
      Description: Internal DNS Namespace for Brighid Services.
      Vpc: !ImportValue cfn-utilities:VpcId

  SigningKey1:
    Type: AWS::KMS::Key
    Properties:
      KeySpec: RSA_4096
      KeyUsage: SIGN_VERIFY
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: kms:*
            Resource: "*"
            Principal:
              AWS: 
                - !Sub arn:aws:iam::${AWS::AccountId}:root

  SigningKey1Alias:
    Type: AWS::KMS::Alias
    Properties:
      TargetKeyId: !GetAtt SigningKey1.Arn
      AliasName: alias/Brighid/SigningKey1

Outputs:
  ClusterName:
    Value: !Ref Cluster
    Description: Name of the ECS Cluster
    Export:
      Name: !Sub ${AWS::StackName}:ClusterName

  RequestTopicArn:
    Value: !Ref RequestTopic
    Description: ARN of the Request / Command Topic
    Export:
      Name: !Sub ${AWS::StackName}:RequestTopicArn

  ResponseTopic:
    Value: !Ref ResponseTopic
    Description: ARN of the Response Topic
    Export:
      Name: !Sub ${AWS::StackName}:ResponseTopicArn

  ServiceRegistry:
    Value: !Ref ServiceRegistry
    Description: Namespace ID of the Service Registry
    Export:
      Name: !Sub ${AWS::StackName}:ServiceRegistry

  ServiceRegistryName:
    Value: !Ref BaseDomainName
    Description: Name of the Service Registry
    Export:
      Name: !Sub ${AWS::StackName}:ServiceRegistryName