version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      docker: 19
  
  build:
    commands:
      - aws s3 cp s3://$ASSETS_SOURCE_BUCKET/$ASSETS_SOURCE_KEY $ASSETS_SOURCE_KEY
      - aws s3 rm s3://$ASSETS_SOURCE_BUCKET/$ASSETS_SOURCE_KEY

artifacts:
  discard-paths: yes
  files:
    - "$ASSETS_SOURCE_KEY"