version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      docker: 19
  
  pre_build:
    commands:
      - . ./cicd/scripts/codebuild-extras.sh

  build:
    commands:
      - ./cicd/scripts/build.sh $ARTIFACT_STORE

artifacts:
  discard-paths: yes
  files:
    - "bin/*"