version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      docker: 19
  
  pre_build:
    commands:
      - . ./cicd/scripts/codebuild-extras.sh

  build:
    commands:
      - ./cicd/scripts/create-config-files.sh

artifacts:
  discard-paths: yes
  files:
    - "cicd/brighid-infrastructure.template.yml"
    - "brighid-infrastructure.*.config.json"