version: 0.2
run-as: root
env:
  shell: bash

phases:
  install:
    runtime-versions:
      docker: 19
      nodejs: 12

    commands:
      - npm --global config set user root
      - npm install --global @cythral/renovate

  build:
    commands:
      - ./cicd/scripts/renovate.sh $ENCRYPTED_GITHUB_TOKEN 
